name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # Required for OIDC

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade "setuptools>=68.0.0" "wheel>=0.40.0" build
      
      - name: Clean build artifacts
        run: rm -rf dist/ build/ *.egg-info/
      
      - name: Build package
        run: python -m build --wheel
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11 